### ISSUE TITLE
World-Gen Config

### ISSUE THREAD

**Issue by SalmonSays** [dblsaiko/QuackLib#10]
Could you at some point make a pass at adding a config option to disable World-Gen for ores? I was working on transitioning Nikolite Ore over to the CoFH World ore generation system this morning to lower the spawn rates a tad and realized it can't be disabled right now, which means the only way to modify the spawn rates is pre-generating a world, using a world editor to replace Nikolite with Air or Stone, and then applying retro-gen with CoFH World to the existing terrain for Nikolite.

**Comment by dblsaiko** [comment]
Yeah, that would definitely be possible

**Comment by TimGoll** [comment]
It's really annoying that Nikolite spawns and you can't disable it. Now I have Nikolite from three different mods ://

**Comment by dblsaiko** [comment]
FYI, I'll implement this after BTM is over, most likely. So, at the beginning of October I guess

**Comment by TimGoll** [comment]
thank you, perfect!

**Comment by dblsaiko** [comment]
I guess this should do the trick for now. Will publish a new version on CurseForge in a bit

**Comment by TimGoll** [comment]
Nice, thank you :)
