### ISSUE TITLE
[Request] Add ability to remove alloy smelter recipes or disable them entirely

### ISSUE THREAD

**Issue by coderbot16** [dblsaiko/QuackLib#12]
I'm making a modpack that includes RetroComputers as a replacement for RP2 computers, alongside some other mods that replace other redpower features. I noticed that this mod includes a bunch of blocks and items that do not appear to have any use, which I am able to remove by disabling crafting recipes and hiding them in JEI with crafttweaker. However, I cannot remove or hide the recipes in the alloy furnace, meaning that players could potentially be confused when looking through JEI. It would be nice if there was just a config option to disable all of the Alloy Furnace recipes, so that I could keep JEI clean. Thanks in advance.

**Comment by dblsaiko** [comment]
What items do you mean? QuackLib should only add items that are needed for RetroComputers. I guess you could go into the jar and delete the `therealfarfetchd/quacklib/common/jei/JEIPlugin.class` file, that should work to disable the JEI plugin at least

**Comment by coderbot16** [comment]
Weird. Here's the modlist if there's anything helpful in it:

```
buildcraft-7.99.17.jar
CodeChickenLib-1.12.2-3.2.0.345-universal.jar
CoFHCore-1.12.2-4.5.2.19-universal.jar
CoFHWorld-1.12.2-1.2.0.5-universal.jar
CraftTweaker2-1.12-4.1.9.jar
Forgelin-1.7.4.jar
ForgeMultipart-1.12.2-2.4.2.60-universal.jar
IC2Classic+1.12-1.5.3.7.jar
jei_1.12.2-4.11.0.202.jar
MCMultiPart-2.5.3.jar
MrTJPCore-1.12.2-2.1.3.35-universal.jar
ProjectRed-1.12.2-4.9.1.92-Base.jar
ProjectRed-1.12.2-4.9.1.92-compat.jar
ProjectRed-1.12.2-4.9.1.92-fabrication.jar
ProjectRed-1.12.2-4.9.1.92-integration.jar
ProjectRed-1.12.2-4.9.1.92-lighting.jar
ProjectRed-1.12.2-4.9.1.92-mechanical.jar
ProjectRed-1.12.2-4.9.1.92-world.jar
quacklib-2.2.5.jar
RebornCore-1.12.2-3.10.0.332-universal.jar
RedstoneFlux-1.12-2.0.2.3-universal.jar
retrocomputers-3.0.1.jar
TechReborn-1.12.2-2.17.3.815-universal.jar
Teckle-master-0.6.471-dirty.jar
ThermalFoundation-1.12.2-2.5.0.19-universal.jar
UniDict-1.12.2-2.7.jar
WanionLib-1.12.2-1.5.jar
```

As well as a screenshot showing the items QuackLib is adding:

![2018-10-06_13 19 50](https://user-images.githubusercontent.com/22420959/46575477-859a5300-c96a-11e8-8c7f-ae3894f20d70.png)

**Comment by dblsaiko** [comment]
Can you post the log file from startup? It shows which items get enabled and why.

**Comment by coderbot16** [comment]
Alright. Note that the log file is rather large because of broken advancements from recipe changes, so I had to trim those out.

Minecraft Log: https://pastebin.com/Nq3avXVM

**Comment by dblsaiko** [comment]
Hm, looks like RetroComputers enables those features despite not using them (look at line 1048-1089). Oh well
Just delete the class file I've told you from the jar

**Comment by coderbot16** [comment]
Ok, will do. In any case, thanks for the help.
