### ISSUE TITLE
QuackLib 2.2.2 RSWires 3.0.0 SpongeForge Crash

### ISSUE THREAD

**Issue by SlayerTheChikken** [dblsaiko/QuackLib#9]
[crash-2018-08-24_16.48.19-server.txt](https://github.com/therealfarfetchd/QuackLib/files/2319059/crash-2018-08-24_16.48.19-server.txt)

This happened after a while, not instant. Public server. Did not happen on 2.1.1, no idea.
Could be a rare issue that's never happened before though, or a one time thing, Ill report back here if it happens again.

**Comment by dblsaiko** [comment]
Redownload the latest version of RSWires. I know it's a bit confusing since there's 3 files with the version 3.0.0, sorry :P

**Comment by SlayerTheChikken** [comment]
Why not make it 3.0.1 or something, that really is confusing lmao

**Comment by dblsaiko** [comment]
I didn't bump the version number because I didn't change any of the code

**Comment by SlayerTheChikken** [comment]
If it doesn't work properly and the newer 3.0.0 version fixes the issue, Id bump the version even with no code changes. But that's just me ;-;

**Comment by dblsaiko** [comment]
I could at least made it 3.0.0-1 or something, yeah. But it's too late for that now :P

**Comment by SlayerTheChikken** [comment]
Yeah, oh well lmao

**Comment by SlayerTheChikken** [comment]
You can close this now if you want, if the issue still occurs Ill reopen
